### ISSUE TITLE
Mancato riscontro a : Questionario per richiesta accreditamento applicativo FSE 2.0

### ISSUE THREAD

**Issue by ZucchettiCentroSistemi** [ministero-salute/it-fse-accreditamento#1223]
Buongiorno,

la presente per avere informazioni riguardo la richiesta di accreditamento per il nostro applicativo, inviata in data 25/01.
Dato che non abbiamo ricevuto alcun tipo di comunicazione, riguardo tale richiesta, volevamo sapere se c’era stato qualche tipo di problema oppure se avevamo commesso qualche errore nella compilazione del questionario.

A disposizione per ulteriori informazioni,

Un saluto

**Comment by smontoli** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
La invitiamo inoltre a seguire il canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) dove vengono puntualmente segnalati eventuali disservizi.
Grazie,

Il team FSE 2.0
