### ISSUE TITLE
Errore nel file data.json

### ISSUE THREAD

**Issue by penny66** [ministero-salute/it-fse-accreditamento#1260]
Buonasera, 
è possibile sapere quali sono gli errori che avere rilevato nel file data.json?

**Comment by smontoli** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
La invitiamo inoltre a seguire il canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) dove vengono puntualmente segnalati eventuali disservizi.
Grazie,

Il team FSE 2.0
