### ISSUE TITLE
Accreditamento procedura di pubblicazione

### ISSUE THREAD

**Issue by lucaerrani** [ministero-salute/it-fse-accreditamento#1300]
Buongiorno,

Come riportato nel README presente [nel repository](https://github.com/ministero-salute/it-fse-accreditamento/blob/main/Test%20Case/README.md), la procedura di pubblicazione non è ancora disponibile per l'accreditamento.

Confermate questa situazione? O è possibile procedere con l'accreditamento anche della pubblicazione?

Grazie

**Comment by smontoli** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
La invitiamo inoltre a seguire il canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) dove vengono puntualmente segnalati eventuali disservizi.
Grazie,

Il team FSE 2.0
