### ISSUE TITLE
Errore 403 in validazione

### ISSUE THREAD

**Issue by embrunoR** [ministero-salute/it-fse-accreditamento#1345]
Buongiorno,
Stiamo provando ad invocare il servizio di validazione con "govway_id": "90efbc26-fbca-11ee-9223-005056ae7395". Stiamo invocando il servizio sia tramite postman, che con CURL. Per entrambe le risposte riceviamo un 403.
L'appId utilizzato nel token è "Gestione Ambulatoriale", e il vendor "Santer Reply".
Potete fornirmi supporto ? Grazie

**Comment by smontoli** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
La invitiamo inoltre a seguire il canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) dove vengono puntualmente segnalati eventuali disservizi.
Grazie,

Il team FSE 2.0
