### ISSUE TITLE
Miglioramento della documentazione dei Test Case

### ISSUE THREAD

**Issue by MasCol75** [ministero-salute/it-fse-accreditamento#1353]
Buongiorno,
abbiamo notato che nel documento dei test case relativo al trasfusionale, è riportata l'indicazione dell'obbligatorietà dei test per i referti di medicina di laboratorio. 
Manca l'indicazione corrispondente nel documento dei test case per i referti di medicina di laboratorio.

**Comment by smontoli** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
La invitiamo inoltre a seguire il canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) dove vengono puntualmente segnalati eventuali disservizi.
Grazie,

Il team FSE 2.0
