### ISSUE TITLE
Nuova pull request - Accreditamento applicativi WINGSR e MEDICALSUITE

### ISSUE THREAD

**Issue by AcsFSE** [ministero-salute/it-fse-accreditamento#1382]
Buongiorno.

Abbiamo creato una nuova pull request , con la correzione dei percorsi di upload dei files  dei 2 applicativi.

Per applicativo WINGSR
commonName auth : A1#111ACSINFORMAT
subject_application_vendor : ACSINFORMATICA
subject_application_id : WINGSR
subject_application_version : V1

Per applicativo MEDICALSUITE
commonName auth : A1#111ACSINFORMAT
subject_application_vendor : ACSINFORMATICA
subject_application_id : MEDICALSUITE
subject_application_version : 1

Grazie.

**Comment by smontoli** [comment]
Buongiorno, 

potreste gentilmente indicarci il link alla vostra nuova PR? 

Un saluto, 
Il team FSE 2.0

**Comment by AcsFSE** [comment]
Salve.

Ecco il link: https://github.com/ministero-salute/it-fse-accreditamento/pull/1383
