### ISSUE TITLE
Accreditamento FSE per referto RSA

### ISSUE THREAD

**Issue by rondellimediam** [ministero-salute/it-fse-accreditamento#1418]
Buongiorno,
dopo aver terminato la fase di validazione del referto con CDA innestato, ci stiamo occupando di quella di accreditamento.
Nello specifico, dobbiamo accreditare un'applicazione che si occupa di nutrizione in ambito ospedaliero e che produce un referto di tipo RSA. Inoltre il nostro scopo è quello di ottenere l'accreditamento per la validazione e non la pubblicazione.
Abbiamo studiato la documentazione da produrre, ma avremmo una serie di dubbi da risolvere, facendo riferimento al file "casi di test RSA" (che alleghiamo), avremmo bisogno di risolvere i seguenti dubbi:

**Caso test 2**
perché dobbiamo occuparci di “test da sforzo – cicloergometro e nella misurazione della pressione arteriosa ogni due minuti durante l’esecuzione” se il nostro referto riguarderà la nutrizione clinica? Non abbiamo questi dati

**Caso test 3**
perché dobbiamo occuparci di “test di ginecologia colposcopia ovvero un esame ginecologico diagnostico di secondo livello che studia le cellule della cervice uterina” se il nostro referto riguarderà la nutrizione clinica? Non abbiamo questi dati

**Caso test 7**
non capiamo se il livello di riservatezza deve mancare (come espresso nel file excel CDA2_Referto_Specialistica_Ambulatoriale_KO) o se deve essere valorizzato come “Restricted”

**Casi test 11, 17, 18, 19, 20, 21** 
Riguardano sezioni non obbligatorie. Bisogna comunque produrre ti test?

Grazie per l'attenzione!

[casi di test RSA.docx](https://github.com/ministero-salute/it-fse-accreditamento/files/15318557/casi.di.test.RSA.docx)
[CDA2_Referto_Specialistica_Ambulatoriale_KO.xlsx](https://github.com/ministero-salute/it-fse-accreditamento/files/15318559/CDA2_Referto_Specialistica_Ambulatoriale_KO.xlsx)

**Comment by smontoli** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
La invitiamo inoltre a seguire il canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) dove vengono puntualmente segnalati eventuali disservizi.
Grazie,

Il team FSE 2.0
