### ISSUE TITLE
Errore accreditamento WRONG_CLAIMS_ON_LOG

### ISSUE THREAD

**Issue by masieroandrea** [ministero-salute/it-fse-accreditamento#1431]
Buonasera,
continuiamo a ricevere lo stesso errore in fase di accreditamento dopo aver fatto il pull:

[ {
 "id" : 6,
 "error" : "WRONG_CLAIMS_ON_LOG",
 "description" : "Claims(appId,appVersion,appVendor) della chiamata al gtw differenti da quelli dichiarati nel data.json"
}, {
 "id" : 6,
 "error" : "WRONG_CLAIMS_ON_LOG",
 "description" : "Claims(appId,appVersion,appVendor) della chiamata al gtw differenti da quelli dichiarati nel data.json"
}, {
 "id" : 6,
 "error" : "WRONG_CLAIMS_ON_LOG",
 "description" : "Claims(appId,appVersion,appVendor) della chiamata al gtw differenti da quelli dichiarati nel data.json"
}, {
 "id" : 369,
 "error" : "WRONG_CLAIMS_ON_LOG",
 "description" : "Claims(appId,appVersion,appVendor) della chiamata al gtw differenti da quelli dichiarati nel data.json"
}, {
 "id" : 369,
 "error" : "WRONG_CLAIMS_ON_LOG",
 "description" : "Claims(appId,appVersion,appVendor) della chiamata al gtw differenti da quelli dichiarati nel data.json"
}, {
 "id" : 369,
 "error" : "WRONG_CLAIMS_ON_LOG",
 "description" : "Claims(appId,appVersion,appVendor) della chiamata al gtw differenti da quelli dichiarati nel data.json"
} ]

Stiamo sbagliando ad inserire appVendor?
Nel survey di accreditamento abbiamo indicato:
- vendor: "Zucchetti Healthcare"
- id: "CSS2"
- version: "2024_10"
Nel path della directory di sottomissione abbiamo rimosso lo spazio del Vendor sostituendolo con _ come da specifiche.
Nelle chiamate al gateway abbiamo utilizzato:
- vendor: "Zucchetti Healthcare"
- id: "CSS2"
- version: "2024_10"

Cosa stiamo sbagliando?

**Comment by smontoli** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
La invitiamo inoltre a seguire il canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) dove vengono puntualmente segnalati eventuali disservizi.
Grazie,

Il team FSE 2.0
