### ISSUE TITLE
Accreditamento DAMP sas

### ISSUE THREAD

**Issue by dampgithub** [ministero-salute/it-fse-accreditamento#1507]
GATEWAY/A1#111#DAMPSOFTWAREXXX/DAMP sas/DAMP - Volare FSE - LIS - RSA/Ver. 02.00

**Comment by smontoli** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
La invitiamo inoltre a seguire il canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) dove vengono puntualmente segnalati eventuali disservizi.
Grazie,

Il team FSE 2.0
