### ISSUE TITLE
Problemi con la "Pull Request"

### ISSUE THREAD

**Issue by dampgithub** [ministero-salute/it-fse-accreditamento#1516]
GATEWAY/A1#111#DAMPSOFTWAREXXX/DAMP sas/DAMP - Volare FSE - LIS - RSA/Ver. 02.00/

Buongiorno, seguendo passo passo l'iter da voi fornito, appena e cerco di aprire la PULL REQUEST mi da il messaggio di errore (Pull request creation failed. Validation failed: must be a collaborator) ...non è che è dato dal problema che è sorto in fase di censimento software house?

Good morning, following the steps you provided, as soon as I try to open the PULL REQUEST, I get the error message (Pull request creation failed. Validation failed: must be a collaborator)... Could this be caused by the issue that arose during the software house registration phase?

**Comment by smontoli** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
La invitiamo inoltre a seguire il canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) dove vengono puntualmente segnalati eventuali disservizi.
Grazie,

Il team FSE 2.0
