### ISSUE TITLE
Discrepanza tra verifica e documentazione HL7IT-IG_CRAD2-v1.1-S.pdf

### ISSUE THREAD

**Issue by RTirabassi-Eurochimica** [ministero-salute/it-fse-accreditamento#1539]
Secondo il capitolo  4.1.13 del documento HL7IT-IG_CRAD2-v1.1-S.pdf  l'elemento <author> deve contenere un elemento <assignedAuthor> il quale a sua volta deve contenere almeno 3 elementi <telecom> che devono riportare la mail, la pec ed il telefono dell'autore.

Nell'approfondire i test di accreditamento abbiamo notato che questa regola non sembra essere coerentemente implementata dal GateWay di test.
In data 2024-07-01 11:24:50 CEST, con "traceID":"e9a5420d616419e1", "spanID":"e9a5420d616419e1", "workflowInstanceId":"2.16.840.1.113883.2.9.2.190.4.4.0c2fe42140ba31337ad7aae7ea627267b2c432f2e1aa8ede9a3625da611f34ce.0a1c0805dc^^^^urn:ihe:iti:xdw:2013:workflowInstanceId" è stato inviato alla validazione un documento il cui CDAv2 è stato volutamente privato di uno dei tre valori (la pec).

Il referto risulta ugualmente validato anche se, da specifica, non dovrebbe. In capitolo del documento citato dice che sono richiesto almeno 3 elementi, porta un esempio con solo 2 di essi lasciando intendere quacosa di diversi, ma nell'esempio del tag completo li riporta tutti e 3.

Sempre nell'ambito della validazione si riscontra che quando l'elemento opzionale <addr> di un paziente viene introdotto, il suo contenuto è parzialmente obbligatorio (elementi <country>, <city> e <streetLineAddress>) ma la presenza dell'elemento anche vuoto risulta sufficiente ad ottenere la validazione. In altri termini il sistema di validazione considera giustamente non corretto l'elelemento mancante, ma considera erroneamente corretto l'elemento presente seppur privo di qualsiasi contenuto.

**Comment by smontoli** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
La invitiamo inoltre a seguire il canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) dove vengono puntualmente segnalati eventuali disservizi.
Grazie,

Il team FSE 2.0
