### ISSUE TITLE
Accreditamento A1#111#TS23XX

### ISSUE THREAD

**Issue by sviluppoTServe** [ministero-salute/it-fse-accreditamento#1552]
Buongiorno,
Vorrei delle delucidazioni sulla situazione dell'accreditamento [A1#111#TS23XX].
Grazie.

**Comment by smontoli** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
La invitiamo inoltre a seguire il canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) dove vengono puntualmente segnalati eventuali disservizi.
Grazie,

Il team FSE 2.0
