### ISSUE TITLE
Abilitazione nuovo Account GitHub

### ISSUE THREAD

**Issue by cbslucalanzano** [ministero-salute/it-fse-accreditamento#1570]
Buongiorno,

avrei bisogno di sapere se fosse possibile aggiungere un'altra persona della nostra organizzazione (quindi attraverso un altro account GitHub) nell'effettuare nuovi fork e pull-request nella vostra repository.

E' fattibile?
Quali sono gli eventuali requisiti?

Grazie

**Comment by smontoli** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
La invitiamo inoltre a seguire il canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) dove vengono puntualmente segnalati eventuali disservizi.
Grazie,

Il team FSE 2.0
