### ISSUE TITLE
Accreditamento FASE1 #1676

### ISSUE THREAD

**Issue by NAMURSRL** [ministero-salute/it-fse-accreditamento#1677]
Ho creato la struttura forkata e eseguito la pull request.
Poteteve verificare se ho eseguito correttamente la procedura di caricamento su GitHub  ?
Vi ringrazio

**Comment by smontoli** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
La invitiamo inoltre a seguire il canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) dove vengono puntualmente segnalati eventuali disservizi.
Grazie,

Il team FSE 2.0
