### ISSUE TITLE
Merge"Revisione accreditamento A1#111EXPRIVIA000 - EXPRIVIA - AURORA - 2 / ERIS -5 #221"

### ISSUE THREAD

**Issue by rangeletti** [ministero-salute/it-fse-accreditamento#258]
Buongiorno la scorsa settimana abbiamo committato un aggiornamento dei file relativi alla richiesta di accreditamento per i nostri prodotti Eris ed Aurora che non risultano ancora visibili nella main. 
Vorremmo sapere se dobbiamo fare altro oltre alla richiesta di merge e quanto occorre affinché vengano recepiti i nostri aggiornamenti.
Grazie.

**Comment by rangeletti** [comment]
Buongiorno,  le nostre richieste di merge per aggiornamenti delle richieste di accreditamento non sembrano essere prese in considerazione. C'è qualcosa che sbagliamo nelle commit?

**Comment by masciamariotti** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
Grazie
