### ISSUE TITLE
Richiesta accreditamento A1#111EBITSRLXXXX/EBITSRL/SUITESTENSA #335

### ISSUE THREAD

**Issue by EbitFSE** [ministero-salute/it-fse-accreditamento#350]
Buongiorno, in merito alla RP in oggetto vi chiediamo se è già stato preso in carico e quando verrà fatto il Merge.
Grazie,
Saluti

**Comment by masciamariotti** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
Grazie
