### ISSUE TITLE
Richiesta verifica per S1#111EUROMEDICAL

### ISSUE THREAD

**Issue by mmaggi69** [ministero-salute/it-fse-accreditamento#480]
Buongiorno, 
vorrei sapere quando verrà effettuato il test per l'accreditamento di S1#111EUROMEDICAL.
Il pull è stato effettuato 2 settimane fa.

**Comment by masciamariotti** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
Grazie
