### ISSUE TITLE
Richiesta accreditamento Euromedica

### ISSUE THREAD

**Issue by mmaggi69** [ministero-salute/it-fse-accreditamento#540]
Buongiorno, ho inviato settimana scorsa 
il file report-checklist.xlsx aggiornato #513. 
Non ho ancora avuto risposta. Potreste verificare ?

**Comment by masciamariotti** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
Grazie
