### ISSUE TITLE
Pull request #937 - Impossibile caricare ulteriori file

### ISSUE THREAD

**Issue by Reev83** [ministero-salute/it-fse-accreditamento#938]
Buongiorno,

ho tentato di creare come da istruzioni un fork del repository e creare la nostra sottocartella per poter caricare i risultati per l'accreditamento.

Al momento l'unica operazione che sono riuscito a fare è il caricamento sulla mia branch del data.json.

Ho tentato invano di caricare il file excel con i report dall'interfaccia web. Il file rimane in caricamento senza dare ulteriori informazioni.
Ho successivamente provato a installare github desktop, dove ho clonato con successo il repository ma tentando di spostarmi sulla mia branch (patch-1) mi viene restituito questo errore :

![image](https://github.com/ministero-salute/it-fse-accreditamento/assets/129532249/621a618d-5931-4273-80d3-509eb277d6b1)

e anche con il git bash il checkout non funziona.

Riuscireste a darci supporto in merito?

Grazie

**Comment by smontoli** [comment]
Buongiorno, per l'apertura delle issue, anche relative all'accreditamento, si rimanda al seguente [link](https://github.com/ministero-salute/it-fse-support/issues). Le issue aperte in it-fse-accreditamento non saranno prese in considerazione.
La invitiamo inoltre a seguire il canale [Slack](https://developersitalia.slack.com/archives/C03RDT88FSM) dove vengono puntualmente segnalati eventuali disservizi.
Grazie
